name: Update IP List

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次
  workflow_dispatch: # 允许手动触发
  push: # 允许提交触发

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        
    - name: Run script (collect IPv4 and IPv6)
      run: python ${{ github.workspace }}/collect_ips.py
        
    - name: Commit and push changes
      run: |
        git config --global user.email "520@proton.me"
        git config --global user.name "520"
        if [ -n "$(git status --porcelain)" ]; then
          git add ipv4.txt ipv6.txt
          git commit -m "Automatic update (IPv4 & IPv6)"
          git push
        else
          echo "No changes detected, skipping commit."
        fi

